FROM golang:1.23-alpine AS builder

WORKDIR /app


COPY EventPlanner_phase1_backend-main/go.mod EventPlanner_phase1_backend-main/go.sum ./


RUN go mod download


COPY EventPlanner_phase1_backend-main/ ./


RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .


FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/


COPY --from=builder /app/main .


EXPOSE 8080


CMD ["./main"]
