FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the app
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

# --- Final Stage ---
FROM alpine:latest

RUN apk --no-cache add ca-certificates

# FIXED: Use /app instead of /root/ to fix Permission Error
WORKDIR /app

# Copy the binary to /app
COPY --from=builder /app/main .

EXPOSE 8080

CMD ["./main"]
